# Default values for fsc-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fscctrlrImage:
  repository: henderiw
  name: fsc-demo-controller
  tag: v0.1.0
  pullPolicy: Always

fscagentImage:
  repository: henderiw
  name: fsc-demo-agent
  tag: v0.1.0
  pullPolicy: Always

imagePullSecrets: []


