---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Namespace }}-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-role
  apiGroup: rbac.authorization.k8s.io
