apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fsc-agent-ds
  labels:
    k8s-app: fscagent
spec:
  selector:
    matchLabels:
      k8s-app: fscagent
  template:
    metadata:
      labels:
        k8s-app: fscagent
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: {{ .Release.Namespace }}-serviceaccount
      containers:
      - name: fsc-demo-agent
        image: {{ .Values.fscagentImage.repository }}/{{ .Values.fscagentImage.name }}:{{ .Values.fscagentImage.tag }}
        imagePullPolicy: {{ .Values.fscagentImage.imagePullPolicy }}
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: lldpd
          mountPath: /var/run/lldpd.socket
        - name: netlinkd
          mountPath: /tmp/netlink.sock
      volumes:
      - name: lldpd
        hostPath:
          path : /var/run/lldpd.socket
      - name: netlinkd
        hostPath:
          path : /tmp/netlink.sock