---
apiVersion: v1
{{- if .Values.imagePullSecret }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecret }}
{{- end }}
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-serviceaccount
